<start>:
     Boxlayout:
          orientation:'vertical'
          Button:
              text: "check"
              id:"check"
              on_press: "root.check()"
          Button:
               text:"Register"
               id:"reg"
               on_press: "root.register() "
          Label:
            text:".. 2024.. "
          Textinput:
              id: "phone"
              text_hint:'type ur message' 
              multi line:True
